services:
  main:
    build: app
    ports:
      - '8020:8020'
    volumes:
      - ./app/db.sqlite3:/app/db.sqlite3
    environment:
      - DJANGO_SUPERUSER_USERNAME=hisu
      - DJANGO_SUPERUSER_PASSWORD=hisu
      - DJANGO_SUPERUSER_EMAIL=hisu@mail.com
