# Generated by Django 4.1.7 on 2023-04-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_numbergame_player_delete_choice_delete_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberGame',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
