# Generated by Django 4.1.7 on 2023-04-25 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_remove_game_type_game_created_at_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nickname',
            field=models.CharField(default='nickname', max_length=16, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Apelido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome'),
        ),
    ]
